version: 2

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - echo ${testitest}

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf